=== usnistgov/ACMVPDocs/Protocol/schema/certificateRequestRegister/certificateRequestRegisterv0.2.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "certificateRequestRegisterPayload",
    "title": "certificateRequestRegisterPayload",
    "description": "Certificate Request Register payload JSON schema",
    "type": "object",
    "additionalProperties": false,
    "required":
    [
        "amvVersion",
        "vendorId",
        "testers",
        "reviewers",
        "module"        
    ],
    "properties":
    {
		"amvVersion": 
        {
			"type": "string"
		},
        "vendorId":
        {
            "type": "integer"
        },
        "testers":
        {
            "type": "array",
            "items":
            {
                "type": "string"
            }
        },
        "reviewers":
        {
            "type": "array",
            "items":
            {
                "type": "string"
            }
        },
        "algorithmCertificates":
        {
            "type": "array",
            "items":
            {
                "type": "string"
            }
        },
        "entropyCertificates":
        {
            "type": "array",
            "items":
            {
                "type": "string"
            }
        },
        "module":
        {
            "description": "The module registration information to be submitted",
            "type": "object",
            "additionalProperties": false,
            "required":
            [
                "schemaVersion",
                "moduleInfo",
                "secLevels",
                "filterProperties"
            ],
            "properties": 
            {
                "schemaVersion":
                {
                    "type": "string"
                },
                "moduleInfo":
                {
                    "type": "object",
                    "properties":
                    {
                        "name": 
                        {
                            "type": "string"
                        },
                        "count": 
                        {
                            "type": "integer"
                        },
                        "description": 
                        {
                            "type": "string"
                        },
                        "embodiment": 
                        {
                            "type": "string"
                        },
                        "type": 
                        {
                            "type": "string"
                        },
                        "opEnvType": 
                        {
                            "type": "string"
                        },
                        "submissionLevel": 
                        {
                            "type": "string"
                        },
                        "itar": 
                        {
                            "type": "boolean"
                        },
                        "overallSecurityLevel": 
                        {
                            "type": "integer"
                        }
                    },
                    "required":
                    [
                        "name",
                        "count",
                        "description",
                        "embodiment",
                        "type",
                        "opEnvType",
                        "submissionLevel",
                        "itar",
                        "overallSecurityLevel"
                    ]
                },
                "secLevels":
                {
                    "type": "array",
                    "items":
                    {
                        "type": "object",
                        "properties":
                        {
                            "section":
                            {
                                "type": "integer"
                            },
                            "level":
                            {
                                "type": "integer"
                            }
                        }
                    }
                },
                "filterProperties":
                {
                    "type": "array",
                    "items":
                    {
                        "type": "object",
                        "properties":
                        {
                            "name":
                            {
                                "type": "string"
                            },
                            "included":
                            {
                                "type": "boolean"
                            }
                        }
                    }
                }

            }
        }
    }
}

=== usnistgov/ACMVPDocs/Protocol/schema/certificateRequestRegister/certificateRequestRegisterv0.2.example.json
{
    "amvVersion": "0.1",
    "vendorId": 1,
    "testers": [
        "CVP-1-000000",
        "CVP-2-000000"

    ],
    "reviewers": [
        "CVP-123456",
        "CVP-789101"
    ],
    "module":
    {
        "schemaVersion": "initial",
        "moduleInfo": 
        {
            "name": "NIST Test Module",
            "count": 1,
            "description": "NIST Postman Test Module",
            "embodiment": "singlechip",
            "type": "software",
            "opEnvType": "modifiable",
            "submissionLevel": "Level 1",
            "itar": false,
            "overallSecurityLevel": 2
        },
        "secLevels": 
        [
            {
                "section": 1,
                "level": 1
            },
            {
                "section": 2,
                "level": 1
            },
            {
                "section": 3,
                "level": 1
            },
            {
                "section": 4,
                "level": 1
            },
            {
                "section": 5,
                "level": 1
            },
            {
                "section": 6,
                "level": 1
            },
            {
                "section": 7,
                "level": 1
            },
            {
                "section": 8,
                "level": 1
            },
            {
                "section": 9,
                "level": 1
            },
            {
                "section": 10,
                "level": 1
            },
            {
                "section": 11,
                "level": 1
            },
            {
                "section": 12,
                "level": 1
            }
        ],
        "filterProperties":
        [
            {"name": "implementsOtar", "included": true},
            {"name": "hasNonApprovedMode", "included": true},
            {"name": "requiresInitialization", "included": true},
            {"name": "hasExcludedComponents", "included": true},
            {"name": "hasDegradedMode", "included": false},
            {"name": "hasPAAorPAI", "included": false},
            {"name": "hasEmbeddedOrBoundModule", "included": false},
            {"name": "hasCriticalFunctions", "included": false},
            {"name": "hasNonApprovedAlgorithmsInApprovedMode", "included": false},
            {"name": "hasExternalInputDevice", "included": false},
            {"name": "hasExternalOutputDevice", "included": false},
            {"name": "usesTrustedChannel", "included": true},
            {"name": "supportsConcurrentOperators", "included": true},
            {"name": "usesIdentityBasedAuthentication", "included": true},
            {"name": "hasMaintenanceRole", "included": true},
            {"name": "allowsOperatorToChangeRoles", "included": false},
            {"name": "hasDefaultAuthenticationData", "included": true},
            {"name": "usesEDC", "included": true},
            {"name": "allowsExternalLoadingOfSoftwareOrFirmware", "included": false},
            {"name": "containsNonReconfigurableMemory", "included": true},
            {"name": "usesOpenSource", "included": false},
            {"name": "providesMaintenanceAccessInterface", "included": false},
            {"name": "hasVentilationOrSlits", "included": false},
            {"name": "hasRemovableCover", "included": false},
            {"name": "hasTamperSeals", "included": false},
            {"name": "hasOperatorAppliedTamperSeals", "included": false},
            {"name": "hasEFPorEFT", "included": false},
            {"name": "outputsSensitiveDataAsPlaintext", "included": false},
            {"name": "supportsManualSSPEntry", "included": true},
            {"name": "usesSplitKnowledge", "included": true},
            {"name": "hasCVE", "included": true},
            {"name": "hasAdditionalMitigations", "included": false},
            {"name": "usesOtherCurve", "included": true},
            {"name": "supportsBypassCapability", "included": false},
            {"name": "hasOTPMemory", "included": false}
        ]
    }
}
